### ISSUE TITLE
python3 port to imodels package

### ISSUE THREAD

**Issue by csinva** [wangtongada/BOA#4]
Hi 👋   thanks for this wonderful work and code release!

We (in the Bin Yu group at UC Berkeley) have been working on [a package](https://github.com/csinva/imodels) for fitting rule-based models and have been wanting to add BOA for a while!

I've just started to integrate it in (file [here](https://github.com/csinva/imodels/blob/master/imodels/rule_set/boa.py) or doc [here](https://csinva.io/imodels/rule_set/boa.html)). Hopefully this common interface can help make BOA very easily accessible to a large audience :smile: The readme links back to this repo too.

Please let me know if you have any issues with this or want to make any tweaks to the implementation there!

Thanks,
Chandan

**Comment by wangtongada** [comment]
Hi Chandan,

sorry for the late reply. I haven't checked github msgs for a while. I'm ok with including BOA in your package. Just to let you know that it has been renamed to Bayesian Rule Set (BRS) in the paper (https://jmlr.org/papers/v18/16-003.html), and I couldn't change the repository name so it still shows BOA in the github link.

**Comment by csinva** [comment]
No problem, thanks for the reply :) And good to know, we'll refer to it as BRS as well then.

**Comment by wangtongada** [comment]
Chandan, I just noticed a bug in setting the parameters. In the function set_parameters, the parameters should be set as: a1=100,b1=1,a2=100,b2=1. It was a1 = 1, b1 = 1, a2 = 100 b2 = 100, and that was incorrect. a1/(a1 + b1) and a2/(a2 + b2) should be a lot bigger than 0.5. They correspond to alpha_+, beta_+ and alpha_- and beta_- from the paper. In fact, these four values play an important role and it needs to be tuned while following the a1/(a1 + b1) >0.5 and a2/(a2 + b2) >0.5 principle

**Comment by csinva** [comment]
Gotcha thanks for letting me know, will update it!

**Comment by wangtongada** [comment]
Sorry Chandan, there was a mistake in my previous reply. Please see the updated reply from above.

**Comment by csinva** [comment]
No problem! Just updated :)
